on:
  push:
    branches:
      - main
    
name: Package

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.FTP_USERNAME }}
            server: ${{ secrets.FTP_SERVER }}
            port: ${{ secrets.FTP_PORT }}
            remote_path: '/public_html'
            sftp_only: true
            password: ${{ secrets.FTP_PASSWORD }}
